### ISSUE TITLE
Web Embed refusing to connect to any web address

### ISSUE THREAD

**Issue by Conor-Behard333** [pad-ws/pad.ws#49]
I have deployed selfhosted pad.ws. Admittedly I've gone off-piste and deployed it to my kubernetes cluster with my own instance of keycloak, coder, and postgres db. But it works well apart from creating any web embed object. any URL I give it (including my coder workspace/terminal link) it shows the following error on the page:

![Image](https://github.com/user-attachments/assets/c6e4e18d-a6d4-4136-a004-ae5f44c21ce3)

**Comment by atyrode** [comment]
Hello! Could you share your console logs, including warning and errors after you've created an embed? I suspect this is related to cross origin/content policies

**Comment by Conor-Behard333** [comment]
Here are the Console logs:
![Image](https://github.com/user-attachments/assets/830c26bf-fef7-442b-ba45-263e7e98b89a)

**Comment by Conor-Behard333** [comment]
Here are the console logs:

![Image](https://github.com/user-attachments/assets/642fc3b3-8029-4f59-b3fc-68e7297c5d95)

**Comment by atyrode** [comment]
Could you confirm that by going in this menu:

<img width="295" alt="Image" src="https://github.com/user-attachments/assets/7d0cdde7-931d-4d5a-af1c-d2005c0244b2" />

And then this menu:

<img width="789" alt="Image" src="https://github.com/user-attachments/assets/93fc43c5-4376-42f4-b620-260c9c1ce15e" />

You either have the same settings, or otherwise, if you set them, does this fix the issue?

**Comment by atyrode** [comment]
Hm. Looking back at these console logs, I also seem a 500 error when trying to ping the API, could you share the logs of the docker container when that happens? Maybe there's some clues over there but I believe your issue is related to how your network is set; it's differing from our setup so I can't tell precisely what is going wrong, but there's some firewall at play not letting your requests through.

In the past, we use to patch the iframes using this logic:

https://gist.github.com/atyrode/110bb16202bf18a734df49288c9ed098

Maybe this will work for you?
You can add this to the sources in the frontend, then modify the index.html to include:

`<script type="module" src="excalidraw-patch.js"></script>`
right above:
`<script type="module" src="index.tsx"></script>`

If this does not cut it, sorry, I'm at loss, and this is probably due to the specificities or your setup, but I'll be on the look out.

**Comment by atyrode** [comment]
Also, I'm noticing in your logs that your app is trying to access "kc.pad.ws" is this intended?
Have you correctly set your `OICD_SERVER_URL` in your `.env`?

**Comment by Conor-Behard333** [comment]
Here are the logs:

> Running hooks in /etc/ca-certificates/update.d...
done.
INFO:     Started server process [1028]
INFO:     Waiting for application startup.
Database connection established successfully
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     10.42.3.38:48800 - "GET /api/user/me HTTP/1.1" 401 Unauthorized
INFO:     10.42.3.38:48796 - "GET /api/workspace/state HTTP/1.1" 401 Unauthorized
INFO:     10.42.3.38:48796 - "GET / HTTP/1.1" 200 OK
INFO:     10.42.3.38:48800 - "GET /api/workspace/state HTTP/1.1" 401 Unauthorized
INFO:     10.42.3.38:48796 - "GET /api/user/me HTTP/1.1" 401 Unauthorized
INFO:     10.42.3.38:48796 - "GET /api/user/me HTTP/1.1" 401 Unauthorized
INFO:     10.42.3.38:48796 - "GET /auth/login?kc_idp_hint=google&popup=1 HTTP/1.1" 307 Temporary Redirect
INFO:     10.42.3.38:48796 - "GET /auth/callback?state=popup&session_state=fca44caa-48d9-49cd-b5a2-c4c87fcf49b3&iss=https%3A%2F%2Fkeycloak.cjhome.uk%2Frealms%2Fmaster&code=cee8f504-84e5-4af5-ab74-06d2fc88bbc2.fca44caa-48d9-49cd-b5a2-c4c87fcf49b3.61b79cc2-67b4-4add-9ea3-d5ddbe9eaec8 HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /assets/index-B44bT6O4.css HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48796 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:53166 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:43486 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:43492 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:36306 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48218 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48218 - "GET / HTTP/1.1" 200 OK
INFO:     10.42.3.38:48420 - "GET /api/user/me HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/user.py", line 23, in get_user_info
    posthog.identify(
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 124, in identify
    return _proxy(
           ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 579, in _proxy
    default_client = Client(
                     ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 257, in __init__
    require("api_key", self.api_key, string_types)
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 1339, in require
    raise AssertionError(msg)
AssertionError: api_key must have (<class 'str'>,), got: None
INFO:     10.42.3.38:48422 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48434 - "GET /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48434 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:48422 - "GET /api/user/me HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/user.py", line 23, in get_user_info
    posthog.identify(
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 124, in identify
    return _proxy(
           ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 579, in _proxy
    default_client = Client(
                     ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 257, in __init__
    require("api_key", self.api_key, string_types)
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 1339, in require
    raise AssertionError(msg)
AssertionError: api_key must have (<class 'str'>,), got: None
INFO:     10.42.3.38:48434 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:48434 - "GET /api/user/me HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/user.py", line 23, in get_user_info
    posthog.identify(
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 124, in identify
    return _proxy(
           ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 579, in _proxy
    default_client = Client(
                     ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 257, in __init__
    require("api_key", self.api_key, string_types)
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 1339, in require
    raise AssertionError(msg)
AssertionError: api_key must have (<class 'str'>,), got: None
INFO:     10.42.3.38:56992 - "GET /assets/Assistant-SemiBold-SCI4bEL9.woff2 HTTP/1.1" 304 Not Modified
INFO:     10.42.3.38:56992 - "GET /api/user/me HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/user.py", line 23, in get_user_info
    posthog.identify(
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 124, in identify
    return _proxy(
           ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 579, in _proxy
    default_client = Client(
                     ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 257, in __init__
    require("api_key", self.api_key, string_types)
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 1339, in require
    raise AssertionError(msg)
AssertionError: api_key must have (<class 'str'>,), got: None
INFO:     10.42.3.38:57000 - "POST /api/canvas HTTP/1.1" 200 OK
INFO:     10.42.3.38:57000 - "GET /api/workspace/state HTTP/1.1" 200 OK
INFO:     10.42.3.38:57000 - "GET /api/user/me HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/user.py", line 23, in get_user_info
    posthog.identify(
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 124, in identify
    return _proxy(
           ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/__init__.py", line 579, in _proxy
    default_client = Client(
                     ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 257, in __init__
    require("api_key", self.api_key, string_types)
  File "/usr/local/lib/python3.11/site-packages/posthog/client.py", line 1339, in require
    raise AssertionError(msg)
AssertionError: api_key must have (<class 'str'>,), got: None

`` 

The errors in the logs only occur when I try going to the "account" settings in the UI. This is when I also get the 500 in the console log. 

I have OICD_SERVER_URL set to my internal keycloak so I'm not sure why kc.pad.ws is showing up at all. Tried the patch you suggested. Still didn't work. 

Interestingly if I try an embedded link from youtube like https://www.youtube.com/embed/2yJgwwDcgV8?si=sPtaLtGhiczrbb8V. it works just fine. So it does point to some issues with my personal coder setup. 

Like I said I've deployed this very differently compared to the docs so it's more than likely something on my end. Appreciate the help tho, if I resolve it I will update this issue

**Comment by atyrode** [comment]
I'm catching a posthog issue right off the bat that shouldn't happen, so I'll merge a fix for that right now, thanks! It could be related to your issue and causing problem further down the line.

Also, I think I've got an idea as to why `kc.pad.ws` got involved out of nowhere, and that might be related to #17 as there is currently an unsolved issue where there is an hardcoded `coder.pad.ws` link in the frontend.

I believe that, if you've previously connected on `pad.ws` and, on your setup, tried to connect using the exact same OICD provider and the same browser, you might actually be tunneling back to us in the background.

If you can, could you try either switching browser/clearing cookies & local storage/connecting with a different provider or account (Github or Google) and see if you still get the issue?

What you should see is that your coder instance will show a login screen, in which case you should use "Sign in with pad"

**Comment by atyrode** [comment]
I've merged a fix;

When that action ends: https://github.com/pad-ws/pad.ws/actions/runs/14741366680/job/41379934850

Could you pull and run the latest version as well as try the solutions I've provided above? I think the error was critical and might have mislead us, and it should at least alleviate part- if not all of the issue!

**Comment by Conor-Behard333** [comment]
Pulled and ran the latest version, resolved all the errors shown in the docker logs associated with posthog and the api 401. 

However, I still can't access coder workspaces. I still get ```Refused to frame 'https://coder.lan/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".``` in the console.log.

**Comment by atyrode** [comment]
Ahhh bummer. I'll dig a bit more and see if I can find a proper and definite fix for you. Thanks for getting back!

**Comment by Conor-Behard333** [comment]
I have manged to resolve the original issue. We were correct in thinking its due to my unique networking config. 

Because I have deployed this on my kubernetes homelab cluster pad-ws has its own domain setup (pad-ws.lan) the same for coder and keycloak. 

On my cluster I use Traefik as my ingress controller, the first thing I needed to do was add custom CSP response headers as middleware for my coder and keycloak ingress (see YAML below). 

```YAML
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: custom-headers
  namespace: coder
spec:
  headers:
    customResponseHeaders:
      X-Frame-Options: SAMEORIGIN
      content-security-policy: "frame-src 'self'; frame-ancestors https://pad-ws.lan; object-src 'none'"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: custom-headers
  namespace: keycloak
spec:
  headers:
    customResponseHeaders:
      X-Frame-Options: SAMEORIGIN
      content-security-policy: "frame-src 'self'; frame-ancestors https://pad-ws.lan; object-src 'none';"
```
Note that the CSP for the frame-ancestors is the url to the pad-ws instance. This differs to the currently documented self hosted deployment as everything runs through localhost on the host network so frame-ancestors can work when set to 'self'. 

This change also needs to happen on the keycloak security defences on the realm settings.

After that everything was able to work
